# Generated by Django 4.0.3 on 2022-03-26 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0002_rename_recipient_list_emails_receiver_one_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emails',
            name='receiver_five',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='emails',
            name='receiver_four',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='emails',
            name='receiver_three',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='emails',
            name='receiver_two',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
